Fix signin redirect dev
Code-the-Dream-School/MyKitchenApp-front pull request #120
Opened 2022-11-29 07:27 UTC by nuriyealp

## Description

Fix sign-in redirection to dashboard
## Resouce links or research articles

## Related Issue
closes #119 

## Acceptance Criteria
Go to the dashboard after login

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     ✓| :bug: Bug fix              |
|   | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates

### Before

### After

## Testing Steps / QA Criteria

Before logging in

- Try to go to private routes like `/dashboard`, `/profile` etc.
- Make sure they are not accessible and redirected to landing page

After logging in

- After clicking sign in, observe user is redirected to `/dashboard`
- Observe correct user name is displayed

2022-11-29 14:36 UTC, XeniyaDob approved these changes
Good job!

2022-11-29 23:10 UTC, elenamagay requested changes
It works now but you have several duplicated routes.

2022-11-29 23:10 UTC, elenamagay commented on src/App.js
> +            />
why routes are duplicated?

2022-12-01 03:29 UTC, nuriyealp commented on src/App.js
> +            />
I fixed it.Thank you!

2022-12-01 16:02 UTC, elenamagay approved these changes
Ok, looks good to me now!
You have some merge conflicts. Please resolve before merging the branch

2022-12-02 04:35 UTC, elenamagay approved these changes

2022-12-02 04:35 UTC, merged